# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sam lau
email: lau@ucsd.edu
github_username: samlau95
description: >
  I am Sam! I'm a PhD student at UC San Diego advised by
  Philip Guo. My research mission is to improve the way we teach
  programming and statistics by designing creative tools for instructors.

logo: "/assets/images/lightbulb.png"
author_image: "/assets/images/sam.jpg"
imageurl: "/assets/images"

paginate: 5 # The number of posts to show per page on your homepage
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:categories/:title"

collections:
  projects:
    output: true
    permalink: /projects/:name

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-github-metadata

sass:
  style: compressed

ga_id: UA-42949369-4
